-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity GATED_SR is
  port (
    WR: in std_logic;
    p_IN: in std_logic;
    p_OUT: out std_logic);
end GATED_SR;

architecture Behavioral of GATED_SR is
  signal OUT_temp: std_logic;
begin
  OUT_temp <= ((OUT_temp OR (p_IN AND WR)) AND NOT (NOT p_IN AND WR));
  p_OUT <= OUT_temp;
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity LATCH_MATRIX_UNIT is
  port (
    ENB_ROW: in std_logic;
    ENB_COL: in std_logic;
    p_IN: in std_logic;
    WR: in std_logic;
    READ: in std_logic;
    p_OUT: out std_logic);
end LATCH_MATRIX_UNIT;

architecture Behavioral of LATCH_MATRIX_UNIT is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
begin
  s2 <= (ENB_COL AND ENB_ROW);
  s0 <= (WR AND s2);
  gate0: entity work.GATED_SR
    port map (
      WR => s0,
      p_IN => p_IN,
      p_OUT => s1);
  p_OUT <= (s1 AND (READ AND s2));
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    ROW_0: in std_logic;
    ROW_1: in std_logic;
    ROW_2: in std_logic;
    ROW_3: in std_logic;
    COL_0: in std_logic;
    COL_1: in std_logic;
    COL_2: in std_logic;
    COL_3: in std_logic;
    WR: in std_logic;
    p_IN: in std_logic;
    READ: in std_logic;
    p_OUT: out std_logic);
end main;

architecture Behavioral of main is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
  signal s8: std_logic;
  signal s9: std_logic;
  signal s10: std_logic;
  signal s11: std_logic;
  signal s12: std_logic;
  signal s13: std_logic;
  signal s14: std_logic;
  signal s15: std_logic;
  signal s16: std_logic;
  signal s17: std_logic_vector(3 downto 0);
  signal s18: std_logic;
  signal s19: std_logic_vector(3 downto 0);
  signal s20: std_logic;
  signal s21: std_logic_vector(3 downto 0);
  signal s22: std_logic;
  signal s23: std_logic_vector(3 downto 0);
  signal s24: std_logic_vector(3 downto 0);
begin
  gate0: entity work.LATCH_MATRIX_UNIT
    port map (
      ENB_ROW => ROW_0,
      ENB_COL => COL_0,
      p_IN => p_IN,
      WR => WR,
      READ => READ,
      p_OUT => s0);
  gate1: entity work.LATCH_MATRIX_UNIT
    port map (
      ENB_ROW => ROW_0,
      ENB_COL => COL_1,
      p_IN => p_IN,
      WR => WR,
      READ => READ,
      p_OUT => s1);
  gate2: entity work.LATCH_MATRIX_UNIT
    port map (
      ENB_ROW => ROW_0,
      ENB_COL => COL_2,
      p_IN => p_IN,
      WR => WR,
      READ => READ,
      p_OUT => s2);
  gate3: entity work.LATCH_MATRIX_UNIT
    port map (
      ENB_ROW => ROW_0,
      ENB_COL => COL_3,
      p_IN => p_IN,
      WR => WR,
      READ => READ,
      p_OUT => s3);
  gate4: entity work.LATCH_MATRIX_UNIT
    port map (
      ENB_ROW => ROW_1,
      ENB_COL => COL_0,
      p_IN => p_IN,
      WR => WR,
      READ => READ,
      p_OUT => s4);
  gate5: entity work.LATCH_MATRIX_UNIT
    port map (
      ENB_ROW => ROW_1,
      ENB_COL => COL_1,
      p_IN => p_IN,
      WR => WR,
      READ => READ,
      p_OUT => s5);
  gate6: entity work.LATCH_MATRIX_UNIT
    port map (
      ENB_ROW => ROW_1,
      ENB_COL => COL_2,
      p_IN => p_IN,
      WR => WR,
      READ => READ,
      p_OUT => s6);
  gate7: entity work.LATCH_MATRIX_UNIT
    port map (
      ENB_ROW => ROW_1,
      ENB_COL => COL_3,
      p_IN => p_IN,
      WR => WR,
      READ => READ,
      p_OUT => s7);
  gate8: entity work.LATCH_MATRIX_UNIT
    port map (
      ENB_ROW => ROW_2,
      ENB_COL => COL_0,
      p_IN => p_IN,
      WR => WR,
      READ => READ,
      p_OUT => s8);
  gate9: entity work.LATCH_MATRIX_UNIT
    port map (
      ENB_ROW => ROW_2,
      ENB_COL => COL_1,
      p_IN => p_IN,
      WR => WR,
      READ => READ,
      p_OUT => s9);
  gate10: entity work.LATCH_MATRIX_UNIT
    port map (
      ENB_ROW => ROW_2,
      ENB_COL => COL_2,
      p_IN => p_IN,
      WR => WR,
      READ => READ,
      p_OUT => s10);
  gate11: entity work.LATCH_MATRIX_UNIT
    port map (
      ENB_ROW => ROW_2,
      ENB_COL => COL_3,
      p_IN => p_IN,
      WR => WR,
      READ => READ,
      p_OUT => s11);
  gate12: entity work.LATCH_MATRIX_UNIT
    port map (
      ENB_ROW => ROW_3,
      ENB_COL => COL_0,
      p_IN => p_IN,
      WR => WR,
      READ => READ,
      p_OUT => s12);
  gate13: entity work.LATCH_MATRIX_UNIT
    port map (
      ENB_ROW => ROW_3,
      ENB_COL => COL_1,
      p_IN => p_IN,
      WR => WR,
      READ => READ,
      p_OUT => s13);
  gate14: entity work.LATCH_MATRIX_UNIT
    port map (
      ENB_ROW => ROW_3,
      ENB_COL => COL_2,
      p_IN => p_IN,
      WR => WR,
      READ => READ,
      p_OUT => s14);
  gate15: entity work.LATCH_MATRIX_UNIT
    port map (
      ENB_ROW => ROW_3,
      ENB_COL => COL_3,
      p_IN => p_IN,
      WR => WR,
      READ => READ,
      p_OUT => s15);
  s17(0) <= s0;
  s17(1) <= s1;
  s17(2) <= s2;
  s17(3) <= s3;
  s19(0) <= s4;
  s19(1) <= s5;
  s19(2) <= s6;
  s19(3) <= s7;
  s21(0) <= s8;
  s21(1) <= s9;
  s21(2) <= s10;
  s21(3) <= s11;
  s23(0) <= s12;
  s23(1) <= s13;
  s23(2) <= s14;
  s23(3) <= s15;
  s16 <= s17(0);
  s18 <= s19(0);
  s20 <= s21(0);
  s22 <= s23(0);
  s24(0) <= s16;
  s24(1) <= s18;
  s24(2) <= s20;
  s24(3) <= s22;
  p_OUT <= s24(0);
end Behavioral;
