-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n4X1_MTPLX_4_REGS is
  port (
    D_0: in std_logic;
    D_1: in std_logic;
    D_2: in std_logic;
    D_3: in std_logic;
    S_1: in std_logic;
    S_0: in std_logic;
    Y: out std_logic);
end n4X1_MTPLX_4_REGS;

architecture Behavioral of n4X1_MTPLX_4_REGS is
begin
  Y <= ((NOT S_0 AND NOT S_1 AND D_0) OR (S_0 AND NOT S_1 AND D_1) OR (NOT S_0 AND S_1 AND D_2) OR (S_0 AND S_1 AND D_3));
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity MASTER_SLAVE_D_TYPE_FLIP_FLOP is
  port (
    DATA: in std_logic;
    CLK: in std_logic;
    Q: out std_logic);
end MASTER_SLAVE_D_TYPE_FLIP_FLOP;

architecture Behavioral of MASTER_SLAVE_D_TYPE_FLIP_FLOP is
  signal s0: std_logic;
  signal s1: std_logic;
  signal Q_temp: std_logic;
begin
  s1 <= NOT (NOT (DATA AND CLK) AND s0);
  s0 <= NOT (s1 AND NOT (CLK AND NOT DATA));
  Q_temp <= NOT (NOT (s1 AND NOT CLK) AND NOT (Q_temp AND NOT (NOT CLK AND s0)));
  Q <= Q_temp;
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity USR_UNIT is
  port (
    CLEAR: in std_logic;
    CLK: in std_logic;
    D_3: in std_logic;
    S_0: in std_logic;
    S_1: in std_logic;
    D_0: in std_logic;
    D_1: in std_logic;
    D_2: in std_logic;
    Q: out std_logic);
end USR_UNIT;

architecture Behavioral of USR_UNIT is
  signal s0: std_logic;
  signal s1: std_logic;
begin
  gate0: entity work.n4X1_MTPLX_4_REGS
    port map (
      D_0 => D_0,
      D_1 => D_1,
      D_2 => D_2,
      D_3 => D_3,
      S_1 => S_1,
      S_0 => S_0,
      Y => s0);
  s1 <= (s0 AND CLEAR);
  gate1: entity work.MASTER_SLAVE_D_TYPE_FLIP_FLOP
    port map (
      DATA => s1,
      CLK => CLK,
      Q => Q);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity USR_RIGHT_SHIFT_UNIT is
  port (
    S_0: in std_logic;
    S_1: in std_logic;
    SI_RIGHT_SHIFT: in std_logic;
    CLEAR: in std_logic;
    CLK: in std_logic;
    D_3: in std_logic;
    D_0: in std_logic;
    D_2: in std_logic;
    Q: out std_logic);
end USR_RIGHT_SHIFT_UNIT;

architecture Behavioral of USR_RIGHT_SHIFT_UNIT is
  signal s0: std_logic;
  signal s1: std_logic;
begin
  gate0: entity work.n4X1_MTPLX_4_REGS
    port map (
      D_0 => D_0,
      D_1 => SI_RIGHT_SHIFT,
      D_2 => D_2,
      D_3 => D_3,
      S_1 => S_1,
      S_0 => S_0,
      Y => s0);
  s1 <= (s0 AND CLEAR);
  gate1: entity work.MASTER_SLAVE_D_TYPE_FLIP_FLOP
    port map (
      DATA => s1,
      CLK => CLK,
      Q => Q);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity USR_LEFT_SHIFT_UNIT is
  port (
    S_0: in std_logic;
    S_1: in std_logic;
    SI_LEFT_SHIFT: in std_logic;
    CLEAR: in std_logic;
    CLK: in std_logic;
    D_3: in std_logic;
    D_0: in std_logic;
    D_1: in std_logic;
    Q: out std_logic);
end USR_LEFT_SHIFT_UNIT;

architecture Behavioral of USR_LEFT_SHIFT_UNIT is
  signal s0: std_logic;
  signal s1: std_logic;
begin
  gate0: entity work.n4X1_MTPLX_4_REGS
    port map (
      D_0 => D_0,
      D_1 => SI_LEFT_SHIFT,
      D_2 => D_1,
      D_3 => D_3,
      S_1 => S_1,
      S_0 => S_0,
      Y => s0);
  s1 <= (s0 AND CLEAR);
  gate1: entity work.MASTER_SLAVE_D_TYPE_FLIP_FLOP
    port map (
      DATA => s1,
      CLK => CLK,
      Q => Q);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    S_0: in std_logic;
    S_1: in std_logic;
    IN_0: in std_logic;
    SI_RIGHT_SHIFT: in std_logic;
    CLEAR: in std_logic;
    CLK: in std_logic;
    IN_1: in std_logic;
    IN_2: in std_logic;
    IN_3: in std_logic;
    IN_4: in std_logic;
    IN_5: in std_logic;
    IN_6: in std_logic;
    IN_7: in std_logic;
    SI_LEFTSHIFT: in std_logic;
    OUT_0: out std_logic;
    OUT_1: out std_logic;
    OUT_2: out std_logic;
    OUT_3: out std_logic;
    OUT_4: out std_logic;
    OUT_5: out std_logic;
    OUT_6: out std_logic;
    OUT_7: out std_logic);
end main;

architecture Behavioral of main is
  signal s0: std_logic;
  signal OUT_0_temp: std_logic;
  signal OUT_1_temp: std_logic;
  signal OUT_2_temp: std_logic;
  signal OUT_3_temp: std_logic;
  signal OUT_4_temp: std_logic;
  signal OUT_5_temp: std_logic;
  signal OUT_6_temp: std_logic;
  signal OUT_7_temp: std_logic;
begin
  s0 <= NOT CLEAR;
  gate0: entity work.USR_UNIT
    port map (
      CLEAR => s0,
      CLK => CLK,
      D_3 => IN_6,
      S_0 => S_0,
      S_1 => S_1,
      D_0 => OUT_6_temp,
      D_1 => OUT_7_temp,
      D_2 => OUT_5_temp,
      Q => OUT_6_temp);
  gate1: entity work.USR_RIGHT_SHIFT_UNIT
    port map (
      S_0 => S_0,
      S_1 => S_1,
      SI_RIGHT_SHIFT => SI_RIGHT_SHIFT,
      CLEAR => s0,
      CLK => CLK,
      D_3 => IN_7,
      D_0 => OUT_7_temp,
      D_2 => OUT_6_temp,
      Q => OUT_7_temp);
  gate2: entity work.USR_UNIT
    port map (
      CLEAR => s0,
      CLK => CLK,
      D_3 => IN_5,
      S_0 => S_0,
      S_1 => S_1,
      D_0 => OUT_5_temp,
      D_1 => OUT_6_temp,
      D_2 => OUT_4_temp,
      Q => OUT_5_temp);
  gate3: entity work.USR_UNIT
    port map (
      CLEAR => s0,
      CLK => CLK,
      D_3 => IN_4,
      S_0 => S_0,
      S_1 => S_1,
      D_0 => OUT_4_temp,
      D_1 => OUT_5_temp,
      D_2 => OUT_3_temp,
      Q => OUT_4_temp);
  gate4: entity work.USR_UNIT
    port map (
      CLEAR => s0,
      CLK => CLK,
      D_3 => IN_3,
      S_0 => S_0,
      S_1 => S_1,
      D_0 => OUT_3_temp,
      D_1 => OUT_4_temp,
      D_2 => OUT_2_temp,
      Q => OUT_3_temp);
  gate5: entity work.USR_UNIT
    port map (
      CLEAR => s0,
      CLK => CLK,
      D_3 => IN_2,
      S_0 => S_0,
      S_1 => S_1,
      D_0 => OUT_2_temp,
      D_1 => OUT_3_temp,
      D_2 => OUT_1_temp,
      Q => OUT_2_temp);
  gate6: entity work.USR_UNIT
    port map (
      CLEAR => s0,
      CLK => CLK,
      D_3 => IN_1,
      S_0 => S_0,
      S_1 => S_1,
      D_0 => OUT_1_temp,
      D_1 => OUT_2_temp,
      D_2 => OUT_0_temp,
      Q => OUT_1_temp);
  gate7: entity work.USR_LEFT_SHIFT_UNIT
    port map (
      S_0 => S_0,
      S_1 => S_1,
      SI_LEFT_SHIFT => SI_LEFTSHIFT,
      CLEAR => s0,
      CLK => CLK,
      D_3 => IN_0,
      D_0 => OUT_0_temp,
      D_1 => OUT_1_temp,
      Q => OUT_0_temp);
  OUT_0 <= OUT_0_temp;
  OUT_1 <= OUT_1_temp;
  OUT_2 <= OUT_2_temp;
  OUT_3 <= OUT_3_temp;
  OUT_4 <= OUT_4_temp;
  OUT_5 <= OUT_5_temp;
  OUT_6 <= OUT_6_temp;
  OUT_7 <= OUT_7_temp;
end Behavioral;
