-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity M_S_DFF_WITH_RESET is
  port (
    DATA: in std_logic;
    CLK: in std_logic;
    CLEAR: in std_logic;
    Q: out std_logic);
end M_S_DFF_WITH_RESET;

architecture Behavioral of M_S_DFF_WITH_RESET is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
begin
  s2 <= NOT CLK;
  s1 <= NOT (NOT (DATA AND CLK) AND s0);
  s0 <= NOT (s1 AND NOT (CLK AND NOT DATA));
  s3 <= NOT (NOT (s1 AND s2) AND NOT (s3 AND NOT (s2 AND s0)));
  Q <= (s3 AND (s2 OR NOT CLEAR));
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    CLK: in std_logic;
    CLEAR: in std_logic;
    COUNT: out std_logic_vector(7 downto 0));
end main;

architecture Behavioral of main is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
  signal s8: std_logic;
begin
  gate0: entity work.M_S_DFF_WITH_RESET
    port map (
      DATA => s0,
      CLK => CLK,
      CLEAR => CLEAR,
      Q => s7);
  gate1: entity work.M_S_DFF_WITH_RESET
    port map (
      DATA => s7,
      CLK => CLK,
      CLEAR => CLEAR,
      Q => s6);
  gate2: entity work.M_S_DFF_WITH_RESET
    port map (
      DATA => s6,
      CLK => CLK,
      CLEAR => CLEAR,
      Q => s5);
  gate3: entity work.M_S_DFF_WITH_RESET
    port map (
      DATA => s5,
      CLK => CLK,
      CLEAR => CLEAR,
      Q => s4);
  gate4: entity work.M_S_DFF_WITH_RESET
    port map (
      DATA => s4,
      CLK => CLK,
      CLEAR => CLEAR,
      Q => s3);
  gate5: entity work.M_S_DFF_WITH_RESET
    port map (
      DATA => s3,
      CLK => CLK,
      CLEAR => CLEAR,
      Q => s2);
  gate6: entity work.M_S_DFF_WITH_RESET
    port map (
      DATA => s2,
      CLK => CLK,
      CLEAR => CLEAR,
      Q => s1);
  gate7: entity work.M_S_DFF_WITH_RESET
    port map (
      DATA => s1,
      CLK => CLK,
      CLEAR => CLEAR,
      Q => s8);
  s0 <= NOT s8;
  COUNT(0) <= s0;
  COUNT(1) <= s1;
  COUNT(2) <= s2;
  COUNT(3) <= s3;
  COUNT(4) <= s4;
  COUNT(5) <= s5;
  COUNT(6) <= s6;
  COUNT(7) <= s7;
end Behavioral;
