/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module MASTER_SLAVE_D_TYPE_FLIP_FLOP (
  input DATA,
  input CLK,
  output Q,
  output \Q' 
);
  wire s0;
  wire s1;
  wire s2;
  wire \Q'_temp ;
  wire Q_temp;
  assign s2 = ~ CLK;
  assign s1 = ~ (~ (DATA & CLK) & s0);
  assign s0 = ~ (s1 & ~ (CLK & ~ DATA));
  assign Q_temp = ~ (~ (s1 & s2) & \Q'_temp );
  assign \Q'_temp  = ~ (Q_temp & ~ (s2 & s0));
  assign Q = Q_temp;
  assign \Q'  = \Q'_temp ;
endmodule

module JOHNSON (
  input CLK,
  output \1 ,
  output \2 ,
  output \3 ,
  output \4 
);
  wire s0;
  wire \1_temp ;
  wire \2_temp ;
  wire s1;
  MASTER_SLAVE_D_TYPE_FLIP_FLOP MASTER_SLAVE_D_TYPE_FLIP_FLOP_i0 (
    .DATA( s0 ),
    .CLK( CLK ),
    .Q( \1_temp  )
  );
  MASTER_SLAVE_D_TYPE_FLIP_FLOP MASTER_SLAVE_D_TYPE_FLIP_FLOP_i1 (
    .DATA( \1_temp  ),
    .CLK( CLK ),
    .Q( \2_temp  )
  );
  MASTER_SLAVE_D_TYPE_FLIP_FLOP MASTER_SLAVE_D_TYPE_FLIP_FLOP_i2 (
    .DATA( \2_temp  ),
    .CLK( CLK ),
    .Q( s1 )
  );
  MASTER_SLAVE_D_TYPE_FLIP_FLOP MASTER_SLAVE_D_TYPE_FLIP_FLOP_i3 (
    .DATA( s1 ),
    .CLK( CLK ),
    .Q( \4  ),
    .\Q' ( s0 )
  );
  assign \1  = \1_temp ;
  assign \2  = \2_temp ;
  assign \3  = CLK;
endmodule
