/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module MASTER_SLAVE_D_TYPE_FLIP_FLOP (
  input DATA,
  input CLK,
  output Q,
  output \Q' 
);
  wire s0;
  wire s1;
  wire s2;
  wire \Q'_temp ;
  wire Q_temp;
  assign s2 = ~ CLK;
  assign s1 = ~ (~ (DATA & CLK) & s0);
  assign s0 = ~ (s1 & ~ (CLK & ~ DATA));
  assign Q_temp = ~ (~ (s1 & s2) & \Q'_temp );
  assign \Q'_temp  = ~ (Q_temp & ~ (s2 & s0));
  assign Q = Q_temp;
  assign \Q'  = \Q'_temp ;
endmodule
